/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package marketapp.marketapp.ProductList;

import java.awt.Graphics;
import java.awt.Image;
import java.beans.PropertyChangeEvent;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import marketapp.marketapp.Order.Pay;
import org.json.simple.*;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author 이영근
 */
public class ProductDetailScreen extends javax.swing.JFrame {

    /**
     * Creates new form ProductDetailScreen
     */
    public static String pName;
    public static String pDesc;
    public static String pPrice;
    public static String[] pInfo;
    public static ImageIcon img;
    public static int totalPrice;

    public static int getTotalPrice() {
        return totalPrice;
    }

    public ProductDetailScreen() {

        imgPane = new JPanel() {
            ImageIcon aa = TableMouse.getImg();
            ImageIcon testimg = new ImageIcon(aa.getImage());

            public void paint(Graphics g) {
                g.drawImage(testimg.getImage(), 0, 0, null);
            }
        };
        imgPane.setSize(350, 300);
        imgPane.setLocation(110, 60);
        this.add(imgPane);

        //setLabel();
        initComponents();
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgLabel = new javax.swing.JLabel();
        imgPane = new javax.swing.JPanel();
        pNameLabel = new javax.swing.JLabel();
        pDescLabel = new javax.swing.JLabel();
        pPriceLabel = new javax.swing.JLabel();
        pCountLabel = new javax.swing.JLabel();
        basketButt = new javax.swing.JButton();
        buyButt = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        descLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        productAmountTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("상품 상세");
        setResizable(false);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        imgLabel.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        imgLabel.setText("이미지");

        imgPane.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                imgPanePropertyChange(evt);
            }
        });

        javax.swing.GroupLayout imgPaneLayout = new javax.swing.GroupLayout(imgPane);
        imgPane.setLayout(imgPaneLayout);
        imgPaneLayout.setHorizontalGroup(
            imgPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );
        imgPaneLayout.setVerticalGroup(
            imgPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
        );

        pNameLabel.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        pNameLabel.setText("상품명 : ");

        pDescLabel.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        pDescLabel.setText("상품설명 :");

        pPriceLabel.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        pPriceLabel.setText("가격 : ");

        pCountLabel.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        pCountLabel.setText("수량 : ");

        basketButt.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        basketButt.setText("장바구니");
        basketButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basketButtActionPerformed(evt);
            }
        });

        buyButt.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        buyButt.setText("구매하기");
        buyButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("맑은 고딕", 0, 16)); // NOI18N
        nameLabel.setText("상품명");
        nameLabel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                nameLabelPropertyChange(evt);
            }
        });

        descLabel.setFont(new java.awt.Font("맑은 고딕", 0, 16)); // NOI18N
        descLabel.setText("상품설명");
        descLabel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                descLabelPropertyChange(evt);
            }
        });

        priceLabel.setFont(new java.awt.Font("맑은 고딕", 0, 16)); // NOI18N
        priceLabel.setText("상품가격");

        productAmountTF.setFont(new java.awt.Font("맑은 고딕", 0, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgLabel)
                .addGap(204, 204, 204))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(basketButt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(buyButt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imgPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pDescLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(descLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(priceLabel)
                                    .addComponent(productAmountTF, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imgPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(descLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pDescLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pCountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productAmountTF, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buyButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(basketButt, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgPanePropertyChange(PropertyChangeEvent evt) {
    }

    private void basketButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basketButtActionPerformed
        // TODO add your handling code here:
        String pName = nameLabel.getText().toString();
        String pPrice = priceLabel.getText().toString();
        String pDesc = descLabel.getText().toString();
        String pAmount = productAmountTF.getText().toString();
        String cartfilePath = "src\\main\\java\\Data\\cartData.json";
        try {
            JSONParser parser = new JSONParser();
            Object obj = parser.parse(new FileReader(cartfilePath));
            JSONObject JsonObj = (JSONObject) obj;
            JSONArray productInfoArr = (JSONArray) JsonObj.get("쇼핑카트");

            JSONObject jObj = new JSONObject();
            jObj.put("Product", pName);
            jObj.put("Price", pPrice);
            jObj.put("Details", pDesc);
            jObj.put("Count", pAmount);

            productInfoArr.add(jObj);
            try {
                FileWriter file = new FileWriter(cartfilePath);
                file.write(JsonObj.toJSONString());
                file.flush();
            } catch (IOException ae) {
                ae.printStackTrace();
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ProductDetailScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ProductDetailScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(ProductDetailScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null, "장바구니에 상품이 담겼습니다.");
        dispose();
    }//GEN-LAST:event_basketButtActionPerformed

    private void buyButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtActionPerformed
        // TODO add your handling code here:
        if (productAmountTF.getText().equals(null) || productAmountTF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "수량을 입력하세요.");
        } else {
            String aa = TableMouse.getPrice();
            String pAmount = productAmountTF.getText().toString();
            int passint = Integer.parseInt(aa);
            int passint2 = Integer.parseInt(pAmount);
            this.totalPrice = passint * passint2;
            String orderPrice = String.valueOf(totalPrice);

            String passProduct = TableMouse.getName() + ", " + pAmount + "개";
            Pay pay = new Pay();
            pay.orderListTA.setText(passProduct);
            pay.orderPriceTF.setText(orderPrice);
            dispose();
        }
    }//GEN-LAST:event_buyButtActionPerformed

    private void nameLabelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_nameLabelPropertyChange
        // TODO add your handling code here:
        this.nameLabel.setText(TableMouse.getName());
    }//GEN-LAST:event_nameLabelPropertyChange

    private void descLabelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_descLabelPropertyChange
        // TODO add your handling code here:
        this.descLabel.setText(TableMouse.getDesc());

    }//GEN-LAST:event_descLabelPropertyChange

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
        this.priceLabel.setText(TableMouse.getPrice());
    }//GEN-LAST:event_formPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton basketButt;
    private javax.swing.JButton buyButt;
    private javax.swing.JLabel descLabel;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JPanel imgPane;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel pCountLabel;
    private javax.swing.JLabel pDescLabel;
    private javax.swing.JLabel pNameLabel;
    private javax.swing.JLabel pPriceLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField productAmountTF;
    // End of variables declaration//GEN-END:variables
}
